name: events_dashboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bot_toast: ^4.1.3
  cloud_firestore: ^4.14.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_app_check: ^0.2.1+8
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
